# Site settings
title: Relationship Doctor
header-img: img/couple.jpg
email: effectivecounselling@gmail.com
description: "With over 40 years experience the relationship doctor can give you unique insights no how to run a happy relationship"
url: "http://relationshipdoctor.co.uk"

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
